version: '3'
services:
  mysql:
    build: ./mysql
#    container_name: v-mysql
    environment:
      MYSQL_DATABASE: smarterp
      MYSQL_ROOT_PASSWORD: smart@vserp
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    ports:
      - "3307:3306"
    volumes:
      - /usr/local/app/smarterp/mysql_data:/var/lib/mysql
    restart: always
  app:
    restart: always
    build: .
    working_dir: /app
    volumes:
      - ./:/app
#      - ~/.m2:/root/.m2
      - /usr/local/app/log:/var/log/smarterp
      # 指定容器时间为宿主机时间
#      - /etc/localtime:/etc/localtime
    environment:
      ERP_ENV: uat
    ports:
      - "9010:9010"
    depends_on:
      - mysql
    command: ./smarterp
#    command: tail -f /dev/null